from pathlib import Path


def replace(path: str, old: str, new: str) -> None:
    file = Path(path)
    text = file.read_text()
    if text.count(old) != 1:
        raise RuntimeError(f"unexpected documentation anchor in {path}: {old[:80]!r}")
    file.write_text(text.replace(old, new, 1))


replace(
    "CHANGELOG.md",
    "- Overlap-safe same-root source semantics at the public builder boundary. Every same-root source is first materialized through an explicit owning C-order `reshape` snapshot before mutation, including shifted overlap, interleaved strides, reversed/permuted layouts, and runtime-symbolic axes; canonical tensor/Buffer/Loop `copy_into` therefore keeps its existing different-root source invariant.\n",
    "- Overlap-safe same-root source semantics at the public builder boundary. Every same-root source is first materialized through an explicit owning C-order `reshape` snapshot before mutation, including shifted overlap, interleaved strides, reversed/permuted layouts, and runtime-symbolic axes; canonical tensor/Buffer/Loop `copy_into` therefore keeps its existing different-root source invariant.\n- Bounded destination-bearing `binary_inplace` effects for exact-typed `add`/`mul` updates of a fresh compiler-owned full storage root from a different storage root, with no extra physical root allocation, explicit storage-generation advancement, direct CPU/C/native mutation, dynamic-specialization and borrowed-source coverage, and serialization-stable operator metadata.\n",
)
replace(
    "CHANGELOG.md",
    "- Writable effects remain limited to compiler-owned internal roots. Runtime-input and constant roots cannot be mutation roots. High-level same-root sources use deterministic snapshot-before-write semantics: the builder materializes the complete logical source into distinct owning storage before the write, so canonical tensor/Buffer/Loop `copy_into` still requires a different-root source even for overlapping, interleaved, reversed, permuted, or runtime-symbolic layouts. Backend `memmove`, broadcasting, casts, general in-place elementwise kernels, and caller-visible mutable output aliases remain out of scope.\n",
    "- Writable effects remain limited to compiler-owned internal roots. Runtime-input and constant roots cannot be mutation roots. High-level same-root `copy_into` sources use deterministic snapshot-before-write semantics. `binary_inplace` is deliberately narrower: it requires a fresh full-root destination, a different-root exact-typed source, and `add` or `mul`. Partial-region in-place binary targets, same-root binary sources, broadcasting, casts, backend `memmove`, and caller-visible mutable output aliases remain out of scope.\n",
)
replace(
    "CHANGELOG.md",
    "- Optimizers remain deliberately conservative in the presence of writable effects: passes that assume a pure expression graph do not reorder, fold, canonicalize, or CSE across `copy_into`, even though verifier-backed fresh generations may be consumed by ordinary computation between ordered writes.\n",
    "- Optimizers remain deliberately conservative in the presence of writable effects: passes that assume a pure expression graph do not reorder, fold, canonicalize, or CSE across `copy_into` or `binary_inplace`, even though verifier-backed fresh generations may be consumed by ordinary computation between ordered writes.\n",
)
replace(
    "README.md",
    "- malformed-IR tests, broadcasting tests, deterministic dump tests, randomized NumPy differential tests, generated-C syntax checks, cross-platform native differential tests, fusion/overflow/generic-DAG regressions, OpenMP scheduling/lifetime regressions, reshape/view/slice/reverse/transpose alias regressions, external-input ABI/cache regressions, multi-output ABI/alias regressions, zero-copy regressions, direct/affine/relational runtime-symbolic specialization regressions, persistent-cache regressions, reusable-native-executable regressions, linting, and CI\n",
    "- malformed-IR tests, broadcasting tests, deterministic dump tests, randomized NumPy differential tests, generated-C syntax checks, cross-platform native differential tests, fusion/overflow/generic-DAG regressions, OpenMP scheduling/lifetime regressions, reshape/view/slice/reverse/transpose alias regressions, writable-copy and bounded in-place-binary generation regressions, external-input ABI/cache regressions, multi-output ABI/alias regressions, zero-copy regressions, direct/affine/relational runtime-symbolic specialization regressions, persistent-cache regressions, reusable-native-executable regressions, linting, and CI\n",
)
replace(
    "README.md",
    "Copied input materialization remains the default compatibility behavior. Opting into `borrow_inputs()` or `compile_module(..., borrow_inputs=True)` / `compile_dynamic_module(..., borrow_inputs=True)` instead requires exact NumPy, C-contiguous, aligned arrays and binds verified external root slots directly; any input that would require a hidden normalization copy is rejected. Read-only view/slice/reverse/transpose handles may then alias that borrowed root without materialization. Subtraction/division, negative symbolic coefficients, nonlinear symbolic products, inequalities, named inputs, runtime-sized physical buffers, inferred `-1` reshape dimensions, generic negative-step slice syntax, writable alias kernels, and runtime permutation axes are not part of the current bounded system.\n",
    "Copied input materialization remains the default compatibility behavior. Opting into `borrow_inputs()` or `compile_module(..., borrow_inputs=True)` / `compile_dynamic_module(..., borrow_inputs=True)` instead requires exact NumPy, C-contiguous, aligned arrays and binds verified external root slots directly; any input that would require a hidden normalization copy is rejected. Read-only view/slice/reverse/transpose handles may then alias that borrowed root without materialization. Writable roots remain compiler-owned: bounded full-root `add`/`mul` in-place effects may consume a different-root exact-typed source, but partial-region binary writes, same-root binary sources, broadcast/cast mutation, inferred `-1` reshape dimensions, generic negative-step slice syntax, and runtime permutation axes are not part of the current bounded system.\n",
)
replace(
    "README.md",
    "Loop IR remains conservative about writes. `LoopAlloc` values are storage roots; `LoopView` values are read-only logical handles with their own `TensorType` and root-relative `StorageLayout`. Kernels may read roots or views but may write only owning roots, and a kernel output may not share a storage root with any input. Every root write advances a generation; stale view handles created against an older generation are rejected on later read or return. Direct, affine, and relational symbolic dimensions are fully resolved before this layer.\n",
    "Loop IR remains conservative about writes. `LoopAlloc` values are storage roots; `LoopView` values are read-only logical handles with their own `TensorType` and root-relative `StorageLayout`. Ordinary kernels may not share an output storage root with any input. Destination-bearing effects are separate verified operations: `copy_into` writes a bounded alias region, while `binary_inplace` updates one fresh full compiler-owned root from a different-root exact-typed source and returns the next logical generation without allocating another physical root. Every root write advances a generation; stale view/root handles created against an older generation are rejected on later read or return. The first in-place binary phase remains serial even when surrounding native execution uses OpenMP. Direct, affine, and relational symbolic dimensions are fully resolved before this layer.\n",
)
replace(
    "README.md",
    "The project now has explicit typed shape transforms, exact runtime shape solving, bounded cost-ranked fusion, expression-driven SSE2, verified native OpenMP scheduling, and a read-only root-relative storage-layout subsystem covering contiguous whole-storage views, positive-stride single-axis slices, explicit signed-stride axis reversals, and arbitrary compile-time axis permutations. Raising fusion-node limits, adding more slice/reverse/permutation spellings, or tuning OpenMP knobs without controlled evidence would be low-value farming. The next CPU-verifiable storage frontier must change alias mutability or overlap semantics—most plausibly verifier-backed writable alias regions with explicit overlap/lifetime rules—while a second executable ISA/backend or accelerator backend remains a parallel architectural option when its toolchain/hardware can be validated.",
    "The project now has explicit typed shape transforms, exact runtime shape solving, bounded cost-ranked fusion, expression-driven SSE2, verified native OpenMP scheduling, read-only root-relative views/slices/reversals/permutations, ordered writable `copy_into` generations with overlap-safe source snapshotting, and bounded full-root `add`/`mul` in-place effects. Raising fusion-node limits, adding more transform spellings, or tuning OpenMP knobs without controlled evidence would be low-value farming. The next CPU-verifiable storage frontier should broaden destination-bearing kernels only where alias proofs remain explicit—most plausibly partial-region in-place elementwise writes with deterministic overlap handling and generation/lifetime checks—while a second executable ISA/backend or accelerator backend remains a parallel architectural option when its toolchain/hardware can be validated."
)
